services:
  postgres:
    image: postgres:14
    container_name: todo-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: todo-db
    ports:
      - "5432:5432"