services:
  postgres:
    image: postgres:14
    container_name: short-url-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: short-url-db
    ports:
      - "5432:5432"