server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo-db
    username: root
    password: qwerty123
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false